const quizHtml = [
  {
    question: 'Wer hat HTML erfunden?',
    answer_1: 'Bob Hope',
    answer_2: 'Lady Gaga',
    answer_3: 'Tim Berbers Lee',
    answer_4: 'Ryan Dahl',
    correctAnswer: 3,
  },
  {
    question: 'Was bedeutet HTML?',
    answer_1: 'HyperText Markup Language',
    answer_2: 'HyperTool Markup Language',
    answer_3: 'Hyperlink Text Markup Language',
    answer_4: 'HomeTool Markup Language',
    correctAnswer: 1,
  },
  {
    question:
      'Welche HTML-Version führte die neuen semantischen Elemente wie -article- und -section- ein?',
    answer_1: 'HTML 4.01',
    answer_2: 'HTML 5',
    answer_3: 'XHTML',
    answer_4: 'HTML 3.2',
    correctAnswer: 2,
  },
  {
    question: 'Welches HTML-Tag wird verwendet, um ein Bild einzufügen?',
    answer_1: '&lt;img&gt;',
    answer_2: '&lt;image&gt;',
    answer_3: '&lt;pic&gt;',
    answer_4: '&lt;picture&gt;',
    correctAnswer: 1,
  },
  {
    question:
      'Welches Attribut wird verwendet, um eine externe CSS-Datei einzubinden?',
    answer_1: '&lt;src&gt;',
    answer_2: '&lt;href&gt;',
    answer_3: '&lt;link&gt;',
    answer_4: '&lt;rel&gt;',
    correctAnswer: 2,
  },
  {
    question: 'Welches HTML-Tag wird verwendet, um einen Absatz zu erstellen?',
    answer_1: 'p',
    answer_2: 'div',
    answer_3: 'span',
    answer_4: 'section',
    correctAnswer: 1,
  },
  {
    question: 'Welches Attribut wird verwendet, um einen Tooltip anzuzeigen?',
    answer_1: 'alt',
    answer_2: 'title',
    answer_3: 'tooltip',
    answer_4: 'hint',
    correctAnswer: 3,
  },
  {
    question: 'Welches Tag wird verwendet, um eine Tabelle zu definieren?',
    answer_1: 'table',
    answer_2: 'tab',
    answer_3: 'tr',
    answer_4: 'td',
    correctAnswer: 1,
  },
  {
    question: 'Wie definierst du eine Tabellenzelle?',
    answer_1: 'cell',
    answer_2: 'th',
    answer_3: 'tr',
    answer_4: 'td',
    correctAnswer: 4,
  },
  {
    question: 'Wie erstellt man eine ungeordnete Liste?',
    answer_1: 'ul',
    answer_2: 'ol',
    answer_3: 'li',
    answer_4: 'list',
    correctAnswer: 1,
  },
  {
    question: 'Wie bindest du ein Video in eine HTML-Seite ein?',
    answer_1: 'video src="video.mp4"',
    answer_2: 'media src="video.mp4"',
    answer_3: 'video url="video.mp4"',
    answer_4: 'embed src="video.mp4"',
    correctAnswer: 1,
  },
  {
    question: 'Welches Attribut gibt die URL einer verlinkten Seite an?',
    answer_1: 'src',
    answer_2: 'href',
    answer_3: 'link',
    answer_4: 'url',
    correctAnswer: 2,
  },
  {
    question: 'Welches Tag wird verwendet, um Text fett darzustellen?',
    answer_1: 'strong',
    answer_2: 'em',
    answer_3: 'bold',
    answer_4: 'b',
    correctAnswer: 4,
  },
  {
    question: 'Wie definierst du ein Eingabefeld in einem Formular?',
    answer_1: 'input',
    answer_2: 'form',
    answer_3: 'field',
    answer_4: 'text',
    correctAnswer: 1,
  },
  {
    question:
      'Welches Tag wird verwendet, um einen Dropdown-Menü zu erstellen?',
    answer_1: 'select',
    answer_2: 'option',
    answer_3: 'dropdown',
    answer_4: 'list',
    correctAnswer: 1,
  },
  {
    question:
      'Welches Attribut wird verwendet, um einem <form>-Tag eine Aktion zuzuweisen?',
    answer_1: 'method',
    answer_2: 'action',
    answer_3: 'type',
    answer_4: 'name',
    correctAnswer: 2,
  },
  {
    question: 'Wie kommentierst du einen HTML-Code?',
    answer_1: '<!-- Kommentar -->',
    answer_2: '// Kommentar',
    answer_3: '/* Kommentar */',
    answer_4: '# Kommentar',
    correctAnswer: 1,
  },
  {
    question:
      'Welches Attribut wird verwendet, um eine ID für ein HTML-Element festzulegen?',
    answer_1: 'id',
    answer_2: 'class',
    answer_3: 'name',
    answer_4: 'type',
    correctAnswer: 1,
  },
  {
    question:
      'Welches Tag wird verwendet, um eine Überschrift der ersten Ebene zu erstellen?',
    answer_1: 'h1',
    answer_2: 'h2',
    answer_3: 'header',
    answer_4: 'title',
    correctAnswer: 1,
  },
  {
    question: 'Wie binde ich eine externe JavaScript-Datei ein?',
    answer_1: '&lt;script src="script.js"&gt;&lt;/script&gt;',
    answer_2: '&lt;javascript src="script.js">&lt;/javascript&gt;',
    answer_3: '&lt;js src="script.js"&gt;&lt;/js&gt;',
    answer_4: '&lt;link src="script.js"&gt;',
    correctAnswer: 1,
  },
  {
    question:
      'Welches Attribut wird verwendet, um eine CSS-Klasse für ein HTML-Element festzulegen?',
    answer_1: 'class',
    answer_2: 'id',
    answer_3: 'style',
    answer_4: 'css',
    correctAnswer: 1,
  },
];
